name: vg_coffee_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_bloc: ^9.1.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  go_router: ^14.8.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  flutter_cache_manager: ^3.4.1
  connectivity_plus: ^6.1.3
  photo_view: ^0.15.0
  file: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  build_runner: ^2.1.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  very_good_analysis: ^7.0.0
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
  generate: true
